-- Comando para armar bd Postgres via Docker
-- docker run --name postgresql -e POSTGRES_USER=dogefox -e POSTGRES_PASSWORD=ctmctmctm -p 5432:5432 -d postgres

CREATE ROLE user_ctm_backend WITH
	LOGIN
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1
	PASSWORD 'ctmctmctm2023';

CREATE DATABASE chapatumancha_db
    WITH
    OWNER = user_ctm_backend
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

drop table if exists cancha;
drop table if exists usuario;

CREATE TABLE USUARIO (
    ID_USUARIO SERIAL PRIMARY KEY,
    NOMBRE TEXT,
    CORREO TEXT,
    PASSWD TEXT,
    DOCUMENTO TEXT,
    CELULAR TEXT
    );
CREATE TABLE CANCHA (
    ID_CANCHA SERIAL PRIMARY KEY,
    ID_USUARIO INTEGER,
    AFORO INTEGER,
    TIPOCANCHA TEXT,
    NOMBRELOCAL TEXT,
    UBICACION TEXT,
    CONSTRAINT FK_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
    );