-- Comando para armar bd Postgres via Docker
-- docker run --name postgresql -e POSTGRES_USER=dogefox -e POSTGRES_PASSWORD=ctmctmctm -p 5432:5432 -d postgres

drop table if exists cancha;
drop table if exists usuario;

CREATE TABLE USUARIO (
    ID_USUARIO INTEGER PRIMARY KEY,
    NOMBRE TEXT,
    CORREO TEXT,
    TIPO TEXT,
    CELULAR TEXT,
    );
CREATE TABLE CANCHA (
    ID_CANCHA INTEGER PRIMARY KEY,
    ID_USUARIO INTEGER,
    AFORO INTEGER,
    TIPOCANCHA TEXT,
    NOMBRELOCAL TEXT,
    UBICACION TEXT,
    CONSTRAINT FK_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
    );

-- drop table sistema;
-- drop table soporte;
-- drop table reserva;
-- drop table arrendador;
-- drop table arrendatario;

/* CREATE TABLE SISTEMA (
    ID_SISTEMA INTEGER PRIMARY KEY,
    NOMBRE TEXT
    );
CREATE TABLE SOPORTE (
    ID_SOPORTE INTEGER PRIMARY KEY,
    HORARIODISPONIBLE TEXT
    );
CREATE TABLE RESERVA (
    ID_RESERVA INTEGER PRIMARY KEY,
    ID_ARRENDATARIO INTEGER,
    FECHA TEXT,
    CANTIDADMAXIMA INTEGER,
    HORAINICIO TEXT,
    HORAFIN TEXT,
    TC TEXT
    );
CREATE TABLE ARRENDADOR(
    ID_ARRENDADOR INTEGER,
    DNI INTEGER,
    NROCUENTABANCARIA INTEGER,
    RESENA TEXT
    );
CREATE TABLE ARRENDATARIO (
    ID_ARRENDATARIO INTEGER PRIMARY KEY,
    DNI INTEGER
    );
CREATE TABLE CANCHA (
    ID_CANCHA INTEGER PRIMARY KEY,
    ID_ARRENDADOR INTEGER,
    AFORO INTEGER,
    TIPOCANCHA TEXT,
    NOMBRELOCAL TEXT,
    UBICACION TEXT);
*/

SELECT *
FROM pg_catalog.pg_tables
WHERE schemaname != 'pg_catalog' AND 
    schemaname != 'information_schema';